export const GET_SEARCH_RESULTS = 'search/GET_SEARCH_RESULTS';
export const GET_SEARCH_RESULTS_SUCCESS = 'search/GET_SEARCH_RESULTS_SUCCESS';
export const GET_SEARCH_RESULTS_ERROR = 'search/GET_SEARCH_RESULTS_ERROR';

export const GET_MOVIE_INFO = 'search/GET_MOVIE_INFO';
export const GET_MOVIE_INFO_SUCCESS = 'search/GET_MOVIE_INFO_SUCCESS';
export const GET_MOVIE_INFO_ERROR = 'search/GET_MOVIE_INFO_ERROR';