export const GET_SEARCH_RESULTS = 'search/GET_SEARCH_RESULTS';
export const GET_SEARCH_RESULTS_SUCCESS = 'search/GET_SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULT_ERROR = 'search/SEARCH_RESULT_ERROR';